const INTERNAL_SERVER_ERROR_CODE = 500;
const NOT_FOUND_ERROR_CODE = 404;
const VALID_ERROR_CODE = 400;
const CREATED_CODE = 201;
const SUCCESS_CODE = 200;
const MONGO_SERVER = 'mongodb://localhost:27017/aroundb';

module.exports = {
  INTERNAL_SERVER_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  VALID_ERROR_CODE,
  CREATED_CODE,
  SUCCESS_CODE,
  MONGO_SERVER,
};
